name = "Dartis-Craft - Testing 2 Early-Mid"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7943c56b5278cc625fe1422be181366cdb8242b4fdffccdf045ec71342c714fe"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
