name = "Dartis-Craft - Testing 2 Early-Mid"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9184c9127ae7b76e0eac16432ab419e29984abe3912552764d6943b53d855554"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
