name = "Dartis-Craft - Testing 2 Early-Mid"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34b0f55f27ff828081bef937c1da288a66dc175bf78c456ac7feb6d79c973613"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
