name = "Dartis-Craft - Testing 2 Early-Mid"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d5c1b010d90ddd76cca6b535c3db3ec18f7cf734b3f922cfd640cae71dcbbd1"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
