name = "Dartis-Craft - Testing 2 Early-Mid"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "729d9bb0fe7ab0abc671206dc756b9e883b0520b859edba3d938dbc3fa3db285"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
