name = "Dartis-Craft - Testing 2 Early-Mid"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d863fd6436f4b7ee874fdbfc1acd73fda3ac4a09c36a0b1c0ee363916cc3af7"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
